const questionsData = [
  // ==========================================
  // 1. ARRAYS (20 Questions)
  // ==========================================
  {
    questionText: 'What is the time complexity to access an element in an array given its index?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Indexing',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(1)' },
      { id: 'B', text: 'O(n)' },
      { id: 'C', text: 'O(log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'Arrays are stored in contiguous memory locations. The address of any element is computed in O(1) constant time using Base Address + (Index * Element Size).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Basics', 'Time Complexity'],
  },
  {
    questionText: 'Which algorithm is used to find the maximum sum of a contiguous subarray in O(n) time and O(1) extra space?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Subarray Problems',
    difficulty: 'easy',
    options: [
      { id: 'A', text: "Kadane's Algorithm" },
      { id: 'B', text: "Dijkstra's Algorithm" },
      { id: 'C', text: "Floyd's Algorithm" },
      { id: 'D', text: "Kruskal's Algorithm" },
    ],
    correctAnswer: 'A',
    explanation: "Kadane's algorithm computes the maximum subarray sum in O(n) time by keeping track of the maximum sum ending at the current position.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Kadane', 'Optimization'],
  },
  {
    questionText: 'Given a sorted array of n integers, what is the most optimal time complexity to find if a pair exists with a given target sum?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Two Pointers',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n) using Two Pointers' },
      { id: 'B', text: 'O(n²) using Nested Loops' },
      { id: 'C', text: 'O(n log n) using Merge Sort' },
      { id: 'D', text: 'O(log n) using Binary Search' },
    ],
    correctAnswer: 'A',
    explanation: 'Because the array is already sorted, we place one pointer at the start and one at the end. Incrementing left if sum < target or decrementing right if sum > target runs in O(n) time with O(1) auxiliary space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Two Pointers'],
  },
  {
    questionText: 'What does a Prefix Sum array enable in O(1) query time?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Prefix Sums',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Range sum queries between index L and R' },
      { id: 'B', text: 'Finding the median of an array' },
      { id: 'C', text: 'Sorting an unsorted array' },
      { id: 'D', text: 'Finding the minimum element in any arbitrary range' },
    ],
    correctAnswer: 'A',
    explanation: 'With a prefix sum array precomputed in O(n), the sum of elements from index L to R is calculated in O(1) time as prefix[R] - prefix[L - 1].',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Prefix Sum'],
  },
  {
    questionText: 'What is the space complexity of reversing an array in-place?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Array Manipulation',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(1)' },
      { id: 'B', text: 'O(n)' },
      { id: 'C', text: 'O(log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'In-place reversal swaps elements from both ends towards the center using a single temporary variable, requiring O(1) auxiliary space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Space Complexity'],
  },
  {
    questionText: 'What is the output of the following C++ code snippet?\nint a[] = {1, 2, 3, 4, 5};\nint *p = a;\ncout << *(p + 2);',
    codeSnippet: 'int a[] = {1, 2, 3, 4, 5};\nint *p = a;\ncout << *(p + 2);',
    questionType: 'code_output',
    topicName: 'Arrays',
    subTopic: 'Pointers & Indexing',
    difficulty: 'easy',
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '2' },
      { id: 'C', text: '4' },
      { id: 'D', text: 'Compilation Error' },
    ],
    correctAnswer: 'A',
    explanation: 'Array name a decays to a pointer to the first element (index 0). Pointer arithmetic *(p + 2) accesses the element at index 2, which is 3.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'C++', 'Pointers'],
  },
  {
    questionText: 'Which technique is ideal for finding the maximum sum of any contiguous subarray of fixed size k?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Sliding Window',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Fixed-size Sliding Window' },
      { id: 'B', text: 'Binary Search' },
      { id: 'C', text: 'Depth First Search' },
      { id: 'D', text: "Floyd-Warshall Algorithm" },
    ],
    correctAnswer: 'A',
    explanation: 'Sliding window computes the sum of the first k elements, then slides across the array by subtracting the element that falls out and adding the new element in O(1) per step, achieving O(n) overall time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Sliding Window'],
  },
  {
    questionText: 'In a 2D array matrix of size M x N stored in Row-Major order, what is the formula to calculate the 1D linear memory offset of element (i, j)?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: '2D Arrays',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'i * N + j' },
      { id: 'B', text: 'j * M + i' },
      { id: 'C', text: 'i * M + j' },
      { id: 'D', text: '(i + j) * N' },
    ],
    correctAnswer: 'A',
    explanation: 'In Row-Major layout, all elements of row 0 are stored first, then row 1, etc. Thus, to reach row i, we skip i * N elements, and then offset by column index j.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Memory Layout'],
  },
  {
    questionText: 'What is the optimal time complexity to find the majority element in an array (an element appearing more than n/2 times)?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Algorithms',
    difficulty: 'medium',
    options: [
      { id: 'A', text: "O(n) time and O(1) space using Boyer-Moore Voting Algorithm" },
      { id: 'B', text: 'O(n log n) time and O(n) space using Sorting' },
      { id: 'C', text: 'O(n²) time using brute force counts' },
      { id: 'D', text: 'O(log n) time using binary search' },
    ],
    correctAnswer: 'A',
    explanation: "Boyer-Moore Voting algorithm finds the majority element in a single pass O(n) with O(1) auxiliary space by canceling out unequal pairs of elements.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Boyer-Moore'],
  },
  {
    questionText: 'How many swaps are needed to rotate an array of size n to the right by k positions using the 3-step Reversal Algorithm?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Rotation',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Total of ~n swaps across 3 reversals' },
      { id: 'B', text: 'O(n²) swaps' },
      { id: 'C', text: 'O(k * n) swaps' },
      { id: 'D', text: 'Exactly k swaps' },
    ],
    correctAnswer: 'A',
    explanation: 'The reversal algorithm reverses the entire array (n/2 swaps), then reverses the first k elements (k/2 swaps), and lastly reverses the remaining n-k elements ((n-k)/2 swaps). Total swaps = n/2 + k/2 + (n-k)/2 = n swaps, achieving O(n) time and O(1) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Array Rotation'],
  },
  {
    questionText: 'Which approach efficiently solves the "Dutch National Flag" problem (sorting an array of 0s, 1s, and 2s)?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Three-way Partitioning',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Three-pointer partitioning (low, mid, high) in a single pass' },
      { id: 'B', text: 'Bubble sort in O(n²)' },
      { id: 'C', text: 'Binary search in O(log n)' },
      { id: 'D', text: 'Recursion with call stack O(n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Dijkstra Dutch National Flag algorithm uses 3 pointers: low, mid, and high to segregate 0s to the left, 1s in the middle, and 2s to the right in O(n) single pass and O(1) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Dutch National Flag'],
  },
  {
    questionText: 'What is the time complexity to find the equilibrium index of an array (where sum of lower indices equals sum of higher indices)?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Prefix Sums',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) time and O(1) auxiliary space' },
      { id: 'B', text: 'O(n²) time' },
      { id: 'C', text: 'O(n log n) time' },
      { id: 'D', text: 'O(2ⁿ) time' },
    ],
    correctAnswer: 'A',
    explanation: 'Calculate the total sum first in O(n). Then iterate through array maintaining leftSum; rightSum = totalSum - leftSum - arr[i]. If leftSum == rightSum, return index. Total time O(n), space O(1).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Equilibrium'],
  },
  {
    questionText: 'When an element is inserted into the middle of a dynamic array (e.g. std::vector or ArrayList) of size n, what is the worst-case time complexity?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Dynamic Arrays',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n) due to shifting subsequent elements' },
      { id: 'B', text: 'O(1)' },
      { id: 'C', text: 'O(log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'Inserting into the middle requires shifting all elements to the right of the insertion index by one position, requiring O(n) operations.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Dynamic Arrays'],
  },
  {
    questionText: 'What is the amortized time complexity of inserting n elements sequentially at the end of a dynamic array that doubles its capacity when full?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Amortized Analysis',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(1) amortized per insertion, O(n) total for n insertions' },
      { id: 'B', text: 'O(n) per insertion' },
      { id: 'C', text: 'O(log n) per insertion' },
      { id: 'D', text: 'O(n²) total' },
    ],
    correctAnswer: 'A',
    explanation: 'Although doubling the capacity takes O(k) copying time, geometric series doubling ensures that total copy operations for n insertions is 1 + 2 + 4 + ... + n < 2n. Hence amortized cost is 2n/n = O(1) per push.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Amortized Analysis'],
  },
  {
    questionText: 'In the "Trapping Rain Water" problem, what is the optimal two-pointer space and time complexity?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Two Pointers',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'Time: O(n), Space: O(1)' },
      { id: 'B', text: 'Time: O(n²), Space: O(1)' },
      { id: 'C', text: 'Time: O(n log n), Space: O(n)' },
      { id: 'D', text: 'Time: O(n), Space: O(n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Using two pointers (left and right) with leftMax and rightMax tracking the boundary heights allows calculating trapped water in O(n) time and O(1) auxiliary space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Two Pointers', 'Hard'],
  },
  {
    questionText: 'What is the time complexity of the "Next Permutation" algorithm on an array of length n?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Permutations',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(n) time and O(1) space' },
      { id: 'B', text: 'O(n log n) time' },
      { id: 'C', text: 'O(n!) time' },
      { id: 'D', text: 'O(2ⁿ) time' },
    ],
    correctAnswer: 'A',
    explanation: 'Next Permutation traverses from right to left to find the first decreasing element, swaps it with the next greater element to the right, and reverses the suffix. All steps take O(n) time and O(1) extra space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Permutations'],
  },
  {
    questionText: 'Given an unsorted array of positive integers, what is the best time complexity to find the maximum product subarray?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Dynamic Programming / Array',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) by maintaining both maxProduct and minProduct' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(n log n)' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'Because multiplying two negative numbers creates a positive number, tracking both current maximum and current minimum product at each step solves it in O(n) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'DP'],
  },
  {
    questionText: 'What is the primary cache-related benefit of arrays over linked lists?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: 'Hardware & Architecture',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Spatial Locality of Reference (contiguous memory prefetching)' },
      { id: 'B', text: 'Dynamic resizing capability' },
      { id: 'C', text: 'Zero pointer memory overhead' },
      { id: 'D', text: 'O(1) insertion at head' },
    ],
    correctAnswer: 'A',
    explanation: 'Because array elements reside contiguously in memory, accessing arr[i] loads adjacent elements (arr[i+1], arr[i+2]) into CPU cache lines automatically, maximizing spatial locality.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Computer Architecture'],
  },
  {
    questionText: 'What is the time complexity to rotate an N x N matrix by 90 degrees clockwise in-place?',
    questionType: 'mcq',
    topicName: 'Arrays',
    subTopic: '2D Matrices',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(N²) time and O(1) space (Transpose then reverse each row)' },
      { id: 'B', text: 'O(N) time and O(N) space' },
      { id: 'C', text: 'O(N³) time and O(1) space' },
      { id: 'D', text: 'O(N log N) time' },
    ],
    correctAnswer: 'A',
    explanation: 'Transposing the matrix (swapping matrix[i][j] with matrix[j][i]) takes O(N²), and reversing each row takes O(N²), yielding in-place 90-degree clockwise rotation with O(1) extra space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Matrix'],
  },
  {
    questionText: 'Can binary search be applied on an unsorted array directly?',
    questionType: 'true_false',
    topicName: 'Arrays',
    subTopic: 'Searching',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'B',
    explanation: 'False. Standard binary search relies strictly on the sorted/monotonic invariant to eliminate half of the search space in each step.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Arrays', 'Binary Search'],
  },

  // ==========================================
  // 2. LINKED LISTS (15 Questions)
  // ==========================================
  {
    questionText: 'What is the time complexity to insert a new node at the head of a Singly Linked List?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Insertion',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(1)' },
      { id: 'B', text: 'O(n)' },
      { id: 'C', text: 'O(log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'Inserting at head only requires setting newNode.next = head and updating head = newNode, which takes constant O(1) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Basics'],
  },
  {
    questionText: 'Which algorithm detects a cycle in a linked list in O(n) time and O(1) auxiliary space?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Cycle Detection',
    difficulty: 'easy',
    options: [
      { id: 'A', text: "Floyd's Tortoise and Hare (Two Pointer) Algorithm" },
      { id: 'B', text: "Kadane's Algorithm" },
      { id: 'C', text: "Dijkstra's Algorithm" },
      { id: 'D', text: "Kruskal's Algorithm" },
    ],
    correctAnswer: 'A',
    explanation: "Floyd's cycle-finding algorithm moves a slow pointer by 1 step and a fast pointer by 2 steps. If a cycle exists, fast will meet slow within O(n) steps.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Floyd Cycle'],
  },
  {
    questionText: 'How many pointer modifications are required to reverse a Singly Linked List of n nodes iteratively?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Reversal',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'n pointer updates, in O(n) time and O(1) space' },
      { id: 'B', text: 'n² pointer updates' },
      { id: 'C', text: '2n pointer updates' },
      { id: 'D', text: 'log n pointer updates' },
    ],
    correctAnswer: 'A',
    explanation: 'Each node has its next pointer redirected to the previous node exactly once as we traverse from head to tail, resulting in n pointer updates.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Reversal'],
  },
  {
    questionText: 'What is the main disadvantage of a Singly Linked List compared to an Array?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Comparison',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'No random access (accessing k-th element takes O(k) time)' },
      { id: 'B', text: 'Fixed size allocation' },
      { id: 'C', text: 'Cannot store dynamic elements' },
      { id: 'D', text: 'Insertion at beginning takes O(n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Arrays allow O(1) random indexing, whereas linked list nodes are scattered across the heap, requiring sequential traversal from head in O(k) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Array Comparison'],
  },
  {
    questionText: 'What is the time complexity to find the middle node of a linked list using the slow/fast pointer technique in a single pass?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Middle Element',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n) time and O(1) auxiliary space' },
      { id: 'B', text: 'O(n²) time' },
      { id: 'C', text: 'O(log n) time' },
      { id: 'D', text: 'O(n) auxiliary space' },
    ],
    correctAnswer: 'A',
    explanation: 'When fast pointer traverses n steps to the end, the slow pointer has traversed exactly n/2 steps to the middle in a single pass O(n) time and O(1) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Two Pointers'],
  },
  {
    questionText: 'In a Doubly Linked List, how much extra memory is used per node compared to a Singly Linked List on a 64-bit architecture?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Doubly Linked List',
    difficulty: 'medium',
    options: [
      { id: 'A', text: '8 bytes (one additional pointer for prev)' },
      { id: 'B', text: '4 bytes' },
      { id: 'C', text: '16 bytes' },
      { id: 'D', text: '0 bytes' },
    ],
    correctAnswer: 'A',
    explanation: 'A 64-bit system uses 8-byte addresses. A Doubly Linked List node stores an additional prev pointer, adding 8 bytes per node.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Memory'],
  },
  {
    questionText: 'How can you find the start node of a cycle in a linked list after detecting cycle intersection using Floyd Tortoise & Hare?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Cycle Start',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'Reset one pointer to head and move both pointers 1 step at a time until they meet' },
      { id: 'B', text: 'Reverse the linked list from intersection' },
      { id: 'C', text: 'Move fast pointer 3 steps at a time' },
      { id: 'D', text: 'It is mathematically impossible without extra memory' },
    ],
    correctAnswer: 'A',
    explanation: 'By the mathematical relation L = k*C - x (distance from head to cycle start equals distance from meeting point to cycle start), moving one pointer from head and one from meeting point at speed 1 causes them to meet exactly at the cycle entrance.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Floyd Proof'],
  },
  {
    questionText: 'What is the optimal time complexity to merge two sorted linked lists of sizes m and n?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Merge Operation',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(m + n) time and O(1) auxiliary space' },
      { id: 'B', text: 'O(m * n) time' },
      { id: 'C', text: 'O(log(m + n)) time' },
      { id: 'D', text: 'O(m + n) auxiliary space' },
    ],
    correctAnswer: 'A',
    explanation: 'By using a dummy head and rewiring existing node next pointers based on comparison, merging takes O(m + n) time and O(1) extra space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Merge'],
  },
  {
    questionText: 'What is the time complexity to find the intersection node of two linked lists of lengths M and N?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Intersection',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(M + N) time and O(1) space' },
      { id: 'B', text: 'O(M * N) time' },
      { id: 'C', text: 'O(M + N) space' },
      { id: 'D', text: 'O(log(M + N))' },
    ],
    correctAnswer: 'A',
    explanation: 'Using two pointers: pointer A travels list A then switches to list B, pointer B travels list B then switches to list A. Both traverse equal distance (M + N) and meet at the intersection node in O(M+N) time and O(1) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Two Pointers'],
  },
  {
    questionText: 'What is the advantage of using a Sentinel (Dummy) Node when performing linked list operations?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Techniques',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Eliminates special edge cases for inserting/deleting the head node' },
      { id: 'B', text: 'Reduces time complexity from O(n) to O(1)' },
      { id: 'C', text: 'Allows bidirectional traversal in singly linked lists' },
      { id: 'D', text: 'Automatically prevents cycles' },
    ],
    correctAnswer: 'A',
    explanation: 'A dummy head ensures that the target node always has a valid preceding node, simplifying pointer rewiring without branching for head modifications.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Design Pattern'],
  },
  {
    questionText: 'In an XOR Linked List, each node stores the XOR of previous and next node addresses. What is the benefit?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Memory Optimization',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'Enables bidirectional traversal using only one pointer field per node' },
      { id: 'B', text: 'Allows O(1) random access by index' },
      { id: 'C', text: 'Prevents memory leaks automatically' },
      { id: 'D', text: 'Replaces hash maps' },
    ],
    correctAnswer: 'A',
    explanation: 'An XOR linked list is a memory-efficient doubly linked list where each node stores address(prev) XOR address(next), saving 50% pointer space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'XOR Linked List'],
  },
  {
    questionText: 'What is the time complexity to remove the N-th node from the end of a linked list in one pass?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Removal',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(L) where L is the total list length' },
      { id: 'B', text: 'O(L²)' },
      { id: 'C', text: 'O(N log L)' },
      { id: 'D', text: 'O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'Advance fast pointer by N steps first. Then move slow and fast together until fast reaches the end; slow will be right before the N-th node from end.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Two Pointers'],
  },
  {
    questionText: 'Which data structure can be implemented efficiently using a Circular Linked List for round-robin CPU scheduling?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Circular Linked List',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Circular Queue' },
      { id: 'B', text: 'Binary Search Tree' },
      { id: 'C', text: 'Disjoint Set Union' },
      { id: 'D', text: 'Monotonic Stack' },
    ],
    correctAnswer: 'A',
    explanation: 'A circular linked list where tail points back to head is the natural structural foundation for round-robin circular queues.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Operating Systems'],
  },
  {
    questionText: 'What is the space complexity of reversing a linked list recursively?',
    questionType: 'mcq',
    topicName: 'Linked Lists',
    subTopic: 'Recursion',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) due to recursion call stack' },
      { id: 'B', text: 'O(1)' },
      { id: 'C', text: 'O(log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'Recursive reversal pushes n function activation frames onto the runtime call stack before unwinding, requiring O(n) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Recursion'],
  },
  {
    questionText: 'Can we delete a given node in a Singly Linked List in O(1) without access to head, assuming the node is not the last node?',
    questionType: 'true_false',
    topicName: 'Linked Lists',
    subTopic: 'Deletion Trick',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'True (Copy value of next node into current node, then delete next node)' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'A',
    explanation: 'True. Set node.val = node.next.val and node.next = node.next.next. This achieves deletion in O(1) time without head reference.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Linked Lists', 'Tricks'],
  },

  // ==========================================
  // 3. STACKS & QUEUES (15 Questions)
  // ==========================================
  {
    questionText: 'What fundamental principle does a Stack follow?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Fundamentals',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'LIFO (Last In, First Out)' },
      { id: 'B', text: 'FIFO (First In, First Out)' },
      { id: 'C', text: 'LILO (Last In, Last Out)' },
      { id: 'D', text: 'Random Order' },
    ],
    correctAnswer: 'A',
    explanation: 'A stack is a linear data structure that adheres to the Last-In, First-Out (LIFO) order.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Basics'],
  },
  {
    questionText: 'Which data structure is used by the system runtime to manage function calls and local variables?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Call Stack',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Call Stack' },
      { id: 'B', text: 'Queue' },
      { id: 'C', text: 'Binary Tree' },
      { id: 'D', text: 'Hash Table' },
    ],
    correctAnswer: 'A',
    explanation: 'The call stack stores stack frames containing return addresses, parameters, and local variables for nested/recursive function executions.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Systems'],
  },
  {
    questionText: 'What is the optimal time complexity to find the Next Greater Element for every element in an array of size n?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Monotonic Stack',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) using a Monotonic Stack' },
      { id: 'B', text: 'O(n²) using nested loops' },
      { id: 'C', text: 'O(n log n) using Priority Queue' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'A monotonic decreasing stack processes each element at most twice (one push, one pop), achieving linear O(n) total time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Monotonic Stack'],
  },
  {
    questionText: 'How can a Min Stack support push, pop, top, and getMin in O(1) time?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Min Stack',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'By maintaining an auxiliary stack that tracks the minimum at each state' },
      { id: 'B', text: 'By sorting the stack after each push' },
      { id: 'C', text: 'By using a binary search tree' },
      { id: 'D', text: 'By using a circular queue' },
    ],
    correctAnswer: 'A',
    explanation: 'An auxiliary min-stack stores the current minimum element encountered so far. When the main stack pops its minimum, the min-stack pops as well, guaranteeing O(1) getMin.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'MinStack'],
  },
  {
    questionText: 'What is the postfix evaluation of the arithmetic expression: 5 3 + 2 * ?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Expression Evaluation',
    difficulty: 'easy',
    options: [
      { id: 'A', text: '16' },
      { id: 'B', text: '11' },
      { id: 'C', text: '25' },
      { id: 'D', text: '30' },
    ],
    correctAnswer: 'A',
    explanation: '5 and 3 are pushed to stack; + pops them and computes 5 + 3 = 8, pushes 8. 2 is pushed. * pops 8 and 2, computes 8 * 2 = 16.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Postfix'],
  },
  {
    questionText: 'How many Queues are required to implement a Stack where push is O(1) and pop is O(n)?',
    questionType: 'mcq',
    topicName: 'Queues',
    subTopic: 'Queue using Stack',
    difficulty: 'medium',
    options: [
      { id: 'A', text: '2 Queues' },
      { id: 'B', text: '1 Queue' },
      { id: 'C', text: '3 Queues' },
      { id: 'D', text: 'Impossible without arrays' },
    ],
    correctAnswer: 'A',
    explanation: 'Using two FIFO queues (q1, q2), enqueue directly into q1. On pop, dequeue n-1 elements from q1 to q2, return the remaining element, and swap queue references.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'Stack Implementation'],
  },
  {
    questionText: 'What is the primary motivation for using a Circular Queue instead of a simple linear array-based queue?',
    questionType: 'mcq',
    topicName: 'Queues',
    subTopic: 'Circular Queue',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'To reuse empty slots at the front created by dequeues without shifting elements' },
      { id: 'B', text: 'To allow random access in O(1)' },
      { id: 'C', text: 'To double capacity automatically' },
      { id: 'D', text: 'To implement priority queues' },
    ],
    correctAnswer: 'A',
    explanation: 'In a simple linear queue, dequeuing leaves unused space at the front. Circular queue uses modulo arithmetic (rear = (rear + 1) % size) to recycle vacated memory in O(1).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'Circular Queue'],
  },
  {
    questionText: 'Which data structure allows insertion and deletion at both ends in O(1) time?',
    questionType: 'mcq',
    topicName: 'Queues',
    subTopic: 'Deque',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Deque (Double-Ended Queue)' },
      { id: 'B', text: 'Monotonic Stack' },
      { id: 'C', text: 'Binary Heap' },
      { id: 'D', text: 'Singly Linked List' },
    ],
    correctAnswer: 'A',
    explanation: 'A Deque (Double-Ended Queue) provides push_front, push_back, pop_front, and pop_back all in O(1) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'Deque'],
  },
  {
    questionText: 'What is the time complexity to find the sliding window maximum of array of size n with window size k using a Monotonic Deque?',
    questionType: 'mcq',
    topicName: 'Queues',
    subTopic: 'Monotonic Deque',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(n) total time' },
      { id: 'B', text: 'O(n * k)' },
      { id: 'C', text: 'O(n log k)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'A monotonic decreasing deque stores indices. Each index is pushed and popped at most once, yielding strictly O(n) amortized time across the entire array.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'Sliding Window'],
  },
  {
    questionText: 'Which data structure is fundamentally utilized to perform Breadth-First Search (BFS) on a graph?',
    questionType: 'mcq',
    topicName: 'Queues',
    subTopic: 'BFS',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'FIFO Queue' },
      { id: 'B', text: 'LIFO Stack' },
      { id: 'C', text: 'Binary Search Tree' },
      { id: 'D', text: 'Disjoint Set' },
    ],
    correctAnswer: 'A',
    explanation: 'BFS explores vertices level by level using a FIFO queue to process neighbor nodes in arrival order.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'BFS'],
  },
  {
    questionText: 'What is the result of converting infix expression (A + B) * C to postfix form?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Infix to Postfix',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'A B + C *' },
      { id: 'B', text: 'A B C + *' },
      { id: 'C', text: '* + A B C' },
      { id: 'D', text: 'A B * C +' },
    ],
    correctAnswer: 'A',
    explanation: 'The parentheses ensure A + B is evaluated first into AB+, then multiplication with C produces AB+C*.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Infix-Postfix'],
  },
  {
    questionText: 'What happens when a pop() is attempted on an empty stack?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Exceptions',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Stack Underflow' },
      { id: 'B', text: 'Stack Overflow' },
      { id: 'C', text: 'Segmentation Fault' },
      { id: 'D', text: 'Deadlock' },
    ],
    correctAnswer: 'A',
    explanation: 'Attempting to remove an element from an empty container triggers a Stack Underflow error.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Underflow'],
  },
  {
    questionText: 'What is the time complexity of the "Largest Rectangle in Histogram" problem using a Monotonic Stack?',
    questionType: 'mcq',
    topicName: 'Stacks',
    subTopic: 'Advanced Stack',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(n) time and O(n) space' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(n log n)' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'A monotonic increasing stack finds the left and right smaller boundaries for every histogram bar in linear O(n) total time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Stacks', 'Histogram', 'Hard'],
  },
  {
    questionText: 'In a priority queue implemented with a binary min-heap, what are the time complexities for insert and extractMin?',
    questionType: 'mcq',
    topicName: 'Queues',
    subTopic: 'Priority Queue',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Insert: O(log n), ExtractMin: O(log n)' },
      { id: 'B', text: 'Insert: O(1), ExtractMin: O(n)' },
      { id: 'C', text: 'Insert: O(n), ExtractMin: O(1)' },
      { id: 'D', text: 'Insert: O(1), ExtractMin: O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'Heap insert appends at the end and bubbles up in O(log n); extractMin replaces root with last element and bubbles down in O(log n).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'Heap'],
  },
  {
    questionText: 'Two stacks can implement a FIFO Queue with amortized O(1) per operation.',
    questionType: 'true_false',
    topicName: 'Queues',
    subTopic: 'Queue using Stacks',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'A',
    explanation: 'True. Enqueue pushes to stackIn. Dequeue pops from stackOut; if stackOut is empty, all elements from stackIn are popped and pushed to stackOut. Each item moves at most twice, yielding amortized O(1).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Queues', 'Amortized'],
  },

  // ==========================================
  // 4. TREES & BST (15 Questions)
  // ==========================================
  {
    questionText: 'Which traversal of a Binary Search Tree (BST) visits the nodes in strictly sorted ascending order?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'BST Traversals',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Inorder Traversal (Left -> Root -> Right)' },
      { id: 'B', text: 'Preorder Traversal (Root -> Left -> Right)' },
      { id: 'C', text: 'Postorder Traversal (Left -> Right -> Root)' },
      { id: 'D', text: 'Level Order Traversal' },
    ],
    correctAnswer: 'A',
    explanation: 'Inorder traversal processes the left subtree (all values < root), the root node, and then the right subtree (all values > root), producing sorted output.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'BST', 'Inorder'],
  },
  {
    questionText: 'What is the maximum number of nodes at depth d in a binary tree (root at depth 0)?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Properties',
    difficulty: 'easy',
    options: [
      { id: 'A', text: '2^d' },
      { id: 'B', text: '2^(d+1)' },
      { id: 'C', text: '2^d - 1' },
      { id: 'D', text: 'd²' },
    ],
    correctAnswer: 'A',
    explanation: 'At depth 0: 2⁰=1, depth 1: 2¹=2, depth 2: 2²=4. In general, maximum nodes at depth d is 2^d.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Math'],
  },
  {
    questionText: 'What is the worst-case time complexity of searching for an element in an unbalanced/skewed BST of n nodes?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'BST Search',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n)' },
      { id: 'B', text: 'O(log n)' },
      { id: 'C', text: 'O(1)' },
      { id: 'D', text: 'O(n log n)' },
    ],
    correctAnswer: 'A',
    explanation: 'In a completely skewed BST (e.g. formed by inserting 1, 2, 3, 4, 5 in order), the tree degrades into a linked list with height n, making search O(n).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'BST Complexity'],
  },
  {
    questionText: 'What is the balance factor condition for every node in an AVL self-balancing binary search tree?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'AVL Trees',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Height(Left Subtree) - Height(Right Subtree) ∈ {-1, 0, +1}' },
      { id: 'B', text: 'Height(Left Subtree) == Height(Right Subtree)' },
      { id: 'C', text: 'Height(Left Subtree) - Height(Right Subtree) <= 2' },
      { id: 'D', text: 'Nodes(Left) == Nodes(Right)' },
    ],
    correctAnswer: 'A',
    explanation: 'In an AVL tree, the balance factor of every node must be -1, 0, or +1. If it violates this after insertion/deletion, tree rotations are performed.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'AVL'],
  },
  {
    questionText: 'What is the time complexity to find the Lowest Common Ancestor (LCA) of two nodes in a Binary Search Tree (BST)?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'LCA',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(h) where h is the tree height' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(2^h)' },
      { id: 'D', text: 'O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'Starting at root: if both p and q are smaller than root, traverse left; if both greater, traverse right; otherwise root is the LCA split point. Takes O(h) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'LCA'],
  },
  {
    questionText: 'When deleting a node with two children in a BST, with what node should it be replaced before deletion?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'BST Deletion',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Inorder Successor (minimum node in right subtree) or Inorder Predecessor' },
      { id: 'B', text: 'The root node' },
      { id: 'C', text: 'Any leaf node' },
      { id: 'D', text: 'The right child directly' },
    ],
    correctAnswer: 'A',
    explanation: 'Replacing with the inorder successor (smallest value in right subtree) maintains the BST ordering invariant across both subtrees.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'BST Deletion'],
  },
  {
    questionText: 'What is the diameter of a binary tree defined as?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Diameter',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'The length of the longest path between any two nodes in the tree' },
      { id: 'B', text: 'The total number of leaves' },
      { id: 'C', text: 'The maximum width at any level' },
      { id: 'D', text: 'The total number of edges from root to deepest leaf' },
    ],
    correctAnswer: 'A',
    explanation: 'The diameter (or width) of a tree is the maximum number of edges or nodes on the longest path between any two leaf nodes in the tree.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Diameter'],
  },
  {
    questionText: 'What data structure is used to serialize and deserialize a binary tree level by level?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Serialization',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Queue (BFS Level Order)' },
      { id: 'B', text: 'Stack (LIFO)' },
      { id: 'C', text: 'Disjoint Set' },
      { id: 'D', text: 'Min-Heap' },
    ],
    correctAnswer: 'A',
    explanation: 'Level order traversal using a Queue serializes nodes depth-by-depth and reconstructs parent-child links during deserialization.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'BFS'],
  },
  {
    questionText: 'In a complete binary tree represented as an array of size n, if a parent node is at index i (0-based), what are the indices of its left and right children?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Array Representation',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Left: 2i + 1, Right: 2i + 2' },
      { id: 'B', text: 'Left: 2i, Right: 2i + 1' },
      { id: 'C', text: 'Left: i/2, Right: i/2 + 1' },
      { id: 'D', text: 'Left: i + 1, Right: i + 2' },
    ],
    correctAnswer: 'A',
    explanation: 'For 0-based indexing: left child is at index 2i + 1, right child is at index 2i + 2, and parent of index k is at floor((k - 1) / 2).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Heaps', 'Indexing'],
  },
  {
    questionText: 'What is the time complexity to build a binary heap from an unsorted array of n elements using Bottom-Up Heapify (Floyd Build-Heap)?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Heapify',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(n)' },
      { id: 'B', text: 'O(n log n)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(log n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Bottom-up heapify runs siftDown from floor(n/2)-1 down to 0. The summation sum(h/2^h) converges to a constant, proving exact linear O(n) bound.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Heaps', 'Math'],
  },
  {
    questionText: 'What is the maximum height of a Red-Black Tree with n internal nodes?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Red-Black Trees',
    difficulty: 'hard',
    options: [
      { id: 'A', text: '2 * log₂(n + 1)' },
      { id: 'B', text: 'log₂(n)' },
      { id: 'C', text: 'n' },
      { id: 'D', text: 'sqrt(n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Due to the red-black invariant that no red node has a red child and all root-to-leaf paths have equal black height, the maximum height is bounded by 2 * log₂(n + 1).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Red-Black Trees'],
  },
  {
    questionText: 'Which tree traversal is commonly used in compilers to evaluate Abstract Syntax Trees (expression trees)?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Expression Trees',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Postorder Traversal (evaluate subtrees before applying operator)' },
      { id: 'B', text: 'Preorder Traversal' },
      { id: 'C', text: 'Level Order Traversal' },
      { id: 'D', text: 'Inorder Traversal' },
    ],
    correctAnswer: 'A',
    explanation: 'Postorder evaluates left operand, then right operand, then applies the operator at the root, directly matching bottom-up syntax tree evaluation.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Compilers'],
  },
  {
    questionText: 'A Trie (Prefix Tree) provides word search operations in time proportional to:',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Trie',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(L) where L is the length of the target string' },
      { id: 'B', text: 'O(N) where N is the total words stored' },
      { id: 'C', text: 'O(log N)' },
      { id: 'D', text: 'O(L * N)' },
    ],
    correctAnswer: 'A',
    explanation: 'In a Trie, each character of the key is traversed as one edge. Search time depends solely on string length L, independent of total dictionary size N.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Trie'],
  },
  {
    questionText: 'Can a binary tree have height 0?',
    questionType: 'true_false',
    topicName: 'Trees',
    subTopic: 'Definitions',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True (A tree with only a root node has height 0)' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'A',
    explanation: 'True. In standard edge-based height definition, a single-node tree with no edges has height 0.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'Definitions'],
  },
  {
    questionText: 'What is the time complexity to check if a binary tree is a valid Binary Search Tree?',
    questionType: 'mcq',
    topicName: 'Trees',
    subTopic: 'Validation',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) time and O(h) space using range validation (-inf, +inf)' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(n log n)' },
      { id: 'D', text: 'O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'By passing valid minimum and maximum constraints recursively to subtrees, every node is checked exactly once in O(n) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Trees', 'BST Validation'],
  },

  // ==========================================
  // 5. GRAPHS (15 Questions)
  // ==========================================
  {
    questionText: 'What is the time complexity of Breadth-First Search (BFS) on a graph with V vertices and E edges using an Adjacency List?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'BFS',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(V + E)' },
      { id: 'B', text: 'O(V * E)' },
      { id: 'C', text: 'O(V²)' },
      { id: 'D', text: 'O(E log V)' },
    ],
    correctAnswer: 'A',
    explanation: 'Every vertex is enqueued once O(V), and all adjacent edges are scanned once O(E), totaling O(V + E).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'BFS Complexity'],
  },
  {
    questionText: 'Which algorithm is used to find the shortest path from a single source in a weighted graph with non-negative edge weights?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Shortest Path',
    difficulty: 'easy',
    options: [
      { id: 'A', text: "Dijkstra's Algorithm" },
      { id: 'B', text: "Kruskal's Algorithm" },
      { id: 'C', text: "Tarjan's Algorithm" },
      { id: 'D', text: "Kosaraju's Algorithm" },
    ],
    correctAnswer: 'A',
    explanation: "Dijkstra's algorithm greedily selects the unvisited node with the lowest provisional distance using a priority queue.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Dijkstra'],
  },
  {
    questionText: 'Why does Dijkstra algorithm fail or produce incorrect results on graphs with negative edge weights?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Dijkstra Limitations',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Because its greedy assumption that visited nodes have finalized shortest distance is violated by negative edges' },
      { id: 'B', text: 'Because it runs in infinite loops always' },
      { id: 'C', text: 'Because priority queues cannot store negative numbers' },
      { id: 'D', text: 'Because it converts graphs to trees' },
    ],
    correctAnswer: 'A',
    explanation: 'Dijkstra assumes that once a vertex is marked visited, its distance cannot be reduced further. A negative edge traversed later can reduce that distance, breaking the invariant. Bellman-Ford must be used instead.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Negative Weights'],
  },
  {
    questionText: 'What is the time complexity of Bellman-Ford algorithm on a graph with V vertices and E edges?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Bellman-Ford',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(V * E)' },
      { id: 'B', text: 'O(V + E)' },
      { id: 'C', text: 'O(E log V)' },
      { id: 'D', text: 'O(V³)' },
    ],
    correctAnswer: 'A',
    explanation: 'Bellman-Ford relaxes all E edges (V - 1) times, resulting in O(V * E) time complexity.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Bellman-Ford'],
  },
  {
    questionText: 'What algorithm can detect negative weight cycles in a directed graph?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Negative Cycles',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Bellman-Ford Algorithm (relaxing edges a V-th time)' },
      { id: 'B', text: "Prim's Algorithm" },
      { id: 'C', text: 'Kahn Topological Sort' },
      { id: 'D', text: 'Binary Search' },
    ],
    correctAnswer: 'A',
    explanation: 'If any distance can still be minimized during a V-th relaxation step in Bellman-Ford, a negative weight cycle exists.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Negative Cycles'],
  },
  {
    questionText: "Which algorithm finds the Minimum Spanning Tree (MST) by sorting edges and using Disjoint Set Union (DSU)?",
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'MST',
    difficulty: 'easy',
    options: [
      { id: 'A', text: "Kruskal's Algorithm" },
      { id: 'B', text: "Prim's Algorithm" },
      { id: 'C', text: "Dijkstra's Algorithm" },
      { id: 'D', text: 'Floyd-Warshall' },
    ],
    correctAnswer: 'A',
    explanation: "Kruskal's algorithm sorts all edges by weight and adds edges greedily using Union-Find to prevent cycle formation.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Kruskal'],
  },
  {
    questionText: 'What is the time complexity of Kruskal algorithm on a graph with E edges and V vertices?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'MST Complexity',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(E log E) or O(E log V)' },
      { id: 'B', text: 'O(V²)' },
      { id: 'C', text: 'O(V + E)' },
      { id: 'D', text: 'O(V * E)' },
    ],
    correctAnswer: 'A',
    explanation: 'Sorting E edges dominates the time at O(E log E). DSU operations with path compression take nearly linear O(E α(V)) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Kruskal'],
  },
  {
    questionText: 'Topological Sort can only be performed on which type of graph?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Topological Sort',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Directed Acyclic Graph (DAG)' },
      { id: 'B', text: 'Undirected Graph with cycles' },
      { id: 'C', text: 'Complete Graph' },
      { id: 'D', text: 'Bipartite Graph with cycles' },
    ],
    correctAnswer: 'A',
    explanation: 'Topological ordering requires a linear ordering of vertices such that for every directed edge u -> v, u comes before v. Cycles make this ordering impossible.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'DAG', 'Topological Sort'],
  },
  {
    questionText: "What is Kahn's algorithm used for in graph theory?",
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Topological Sort',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Topological Sorting using In-Degree counts and a Queue' },
      { id: 'B', text: 'Finding All-Pairs Shortest Path' },
      { id: 'C', text: 'Graph Coloring' },
      { id: 'D', text: 'Finding Maximum Bipartite Matching' },
    ],
    correctAnswer: 'A',
    explanation: "Kahn's algorithm maintains in-degrees of all vertices and repeatedly removes vertices with 0 in-degree using a queue.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Kahn'],
  },
  {
    questionText: 'What is the time complexity of the Floyd-Warshall All-Pairs Shortest Path algorithm for a graph with V vertices?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'All-Pairs Shortest Path',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(V³)' },
      { id: 'B', text: 'O(V²)' },
      { id: 'C', text: 'O(V * E log V)' },
      { id: 'D', text: 'O(2^V)' },
    ],
    correctAnswer: 'A',
    explanation: 'Floyd-Warshall uses 3 nested loops over all vertices (k, i, j) to compute dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]), requiring O(V³) time and O(V²) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Floyd-Warshall'],
  },
  {
    questionText: 'A graph is Bipartite if and only if:',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Bipartite',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'It contains NO odd-length cycles' },
      { id: 'B', text: 'It is a Directed Acyclic Graph' },
      { id: 'C', text: 'It is a Complete Graph' },
      { id: 'D', text: 'All vertices have even degrees' },
    ],
    correctAnswer: 'A',
    explanation: 'A graph is 2-colorable (bipartite) if and only if it contains no cycles of odd length.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Bipartite'],
  },
  {
    questionText: "What are the two passes in Kosaraju's Algorithm for finding Strongly Connected Components (SCCs)?",
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'SCC',
    difficulty: 'hard',
    options: [
      { id: 'A', text: '1. DFS to get finishing order; 2. DFS on Transposed Graph in reverse finishing order' },
      { id: 'B', text: '1. BFS from source; 2. Dijkstra from destination' },
      { id: 'C', text: '1. Kruskal MST; 2. Prim MST' },
      { id: 'D', text: '1. Topological sort; 2. Floyd-Warshall' },
    ],
    correctAnswer: 'A',
    explanation: "Kosaraju's algorithm finds SCCs in O(V + E) by computing completion times via DFS, reversing all directed edges, and running DFS on the transposed graph.",
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'SCC', 'Kosaraju'],
  },
  {
    questionText: 'How many edges does a spanning tree of a connected graph with V vertices have?',
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Spanning Tree',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'V - 1' },
      { id: 'B', text: 'V' },
      { id: 'C', text: 'V + 1' },
      { id: 'D', text: '2V' },
    ],
    correctAnswer: 'A',
    explanation: 'A tree with V vertices has exactly V - 1 edges and no cycles.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Spanning Tree'],
  },
  {
    questionText: 'In an undirected graph, the sum of degrees of all vertices equals twice the total number of edges (Handshaking Lemma).',
    questionType: 'true_false',
    topicName: 'Graphs',
    subTopic: 'Graph Theory',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'A',
    explanation: 'True. Every undirected edge contributes +1 degree to each of its two endpoint vertices, so sum(deg(v)) = 2 * |E|.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'Handshaking Lemma'],
  },
  {
    questionText: "What is the amortized time complexity of Union-Find with Path Compression and Union by Rank?",
    questionType: 'mcq',
    topicName: 'Graphs',
    subTopic: 'Disjoint Set',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(α(n)) per operation (Inverse Ackermann function, practically constant <= 4)' },
      { id: 'B', text: 'O(log n)' },
      { id: 'C', text: 'O(n)' },
      { id: 'D', text: 'O(1) strict worst-case' },
    ],
    correctAnswer: 'A',
    explanation: 'Combining path compression and rank optimization yields amortized O(α(n)) per operation, where α(n) is the inverse Ackermann function.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Graphs', 'DSU', 'Hard'],
  },

  // ==========================================
  // 6. SORTING & SEARCHING (10 Questions)
  // ==========================================
  {
    questionText: 'What is the theoretical lower bound for comparison-based sorting algorithms in the worst case?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'Complexity Bounds',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Ω(n log n)' },
      { id: 'B', text: 'Ω(n)' },
      { id: 'C', text: 'Ω(n²)' },
      { id: 'D', text: 'Ω(log n)' },
    ],
    correctAnswer: 'A',
    explanation: 'A comparison decision tree with n! permutations has depth at least log₂(n!) = Ω(n log n) by Stirling approximation.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Theory'],
  },
  {
    questionText: 'Which sorting algorithm is Stable, Out-of-place, and guarantees O(n log n) worst-case time complexity?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'Merge Sort',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Merge Sort' },
      { id: 'B', text: 'Quick Sort' },
      { id: 'C', text: 'Heap Sort' },
      { id: 'D', text: 'Selection Sort' },
    ],
    correctAnswer: 'A',
    explanation: 'Merge sort always splits and merges in O(n log n) worst case, preserves relative order of duplicate keys (stable), and uses O(n) auxiliary memory.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Merge Sort'],
  },
  {
    questionText: 'What is the worst-case time complexity of standard Quick Sort, and when does it occur?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'Quick Sort',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n²) when the pivot chosen is always the smallest or largest element' },
      { id: 'B', text: 'O(n log n) always' },
      { id: 'C', text: 'O(n) when array is already sorted' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'If the pivot divides the array into subproblems of size 0 and n-1 at each step, recurrence T(n) = T(n-1) + O(n) resolves to O(n²).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Quick Sort'],
  },
  {
    questionText: 'Which sorting algorithm has the minimum number of memory write/swap operations (at most n-1 swaps)?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'Selection Sort',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Selection Sort' },
      { id: 'B', text: 'Bubble Sort' },
      { id: 'C', text: 'Insertion Sort' },
      { id: 'D', text: 'Merge Sort' },
    ],
    correctAnswer: 'A',
    explanation: 'Selection sort finds the minimum element and performs at most 1 swap per outer iteration, totaling at most n-1 swaps, making it ideal when write operations are expensive (e.g. Flash EEPROM).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Selection Sort'],
  },
  {
    questionText: 'What is the best-case time complexity of Insertion Sort on an already sorted array?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'Insertion Sort',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n)' },
      { id: 'B', text: 'O(n log n)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'When the array is already sorted, insertion sort makes 1 comparison per element and 0 shifts, achieving O(n) linear time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Insertion Sort'],
  },
  {
    questionText: 'Which non-comparison sorting algorithm runs in O(n + k) time where k is the range of non-negative integers?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'Counting Sort',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Counting Sort' },
      { id: 'B', text: 'Quick Sort' },
      { id: 'C', text: 'Heap Sort' },
      { id: 'D', text: 'Shell Sort' },
    ],
    correctAnswer: 'A',
    explanation: 'Counting sort counts occurrences of each value in an auxiliary frequency array of size k, running in O(n + k) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Counting Sort'],
  },
  {
    questionText: 'What is the time complexity to search for a target element in a Rotated Sorted Array of size n with unique elements?',
    questionType: 'mcq',
    topicName: 'Searching',
    subTopic: 'Rotated Array',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(log n) using modified Binary Search' },
      { id: 'B', text: 'O(n)' },
      { id: 'C', text: 'O(n log n)' },
      { id: 'D', text: 'O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'By identifying whether the left or right sub-array is strictly sorted, we discard half the array in each iteration, preserving O(log n) binary search.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Searching', 'Binary Search'],
  },
  {
    questionText: 'In Binary Search, how should mid index be calculated to prevent integer 32-bit overflow?',
    questionType: 'mcq',
    topicName: 'Searching',
    subTopic: 'Implementation Details',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'mid = left + (right - left) / 2' },
      { id: 'B', text: 'mid = (left + right) / 2' },
      { id: 'C', text: 'mid = (left + right) >> 2' },
      { id: 'D', text: 'mid = right - left / 2' },
    ],
    correctAnswer: 'A',
    explanation: 'When left + right exceeds INT_MAX (2^31 - 1), (left + right) overflows to a negative integer. left + (right - left) / 2 avoids overflow completely.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Searching', 'Integer Overflow'],
  },
  {
    questionText: 'What is the time complexity of finding the k-th smallest element in an unsorted array of size n using the QuickSelect algorithm on average?',
    questionType: 'mcq',
    topicName: 'Sorting',
    subTopic: 'QuickSelect',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) on average' },
      { id: 'B', text: 'O(n log n)' },
      { id: 'C', text: 'O(k log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'QuickSelect only recurses into one partition (instead of both like QuickSort), resulting in n + n/2 + n/4 + ... = 2n = O(n) average time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'QuickSelect'],
  },
  {
    questionText: 'Heap Sort is an in-place sorting algorithm that is NOT stable.',
    questionType: 'true_false',
    topicName: 'Sorting',
    subTopic: 'Heap Sort Properties',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'A',
    explanation: 'True. Heap Sort uses O(1) auxiliary space (in-place) but can alter the relative order of duplicate elements during heapify swaps (unstable).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Sorting', 'Heap Sort'],
  },

  // ==========================================
  // 7. DYNAMIC PROGRAMMING (10 Questions)
  // ==========================================
  {
    questionText: 'What are the two key properties a problem must exhibit to be solvable via Dynamic Programming?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'Foundations',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Optimal Substructure and Overlapping Subproblems' },
      { id: 'B', text: 'Greedy Choice and Non-overlapping Subproblems' },
      { id: 'C', text: 'Randomized Pivoting and Independent States' },
      { id: 'D', text: 'LIFO property and Contiguous Memory' },
    ],
    correctAnswer: 'A',
    explanation: 'DP applies when an optimal solution can be constructed from optimal subproblem solutions (Optimal Substructure) and the same subproblems are solved repeatedly (Overlapping Subproblems).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'Concepts'],
  },
  {
    questionText: 'What is the time and space complexity of the 0/1 Knapsack Problem with N items and maximum weight capacity W?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: '0/1 Knapsack',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Time: O(N * W), Space: O(N * W) (optimizable to O(W))' },
      { id: 'B', text: 'Time: O(2^N), Space: O(1)' },
      { id: 'C', text: 'Time: O(N log W), Space: O(N)' },
      { id: 'D', text: 'Time: O(N + W), Space: O(N)' },
    ],
    correctAnswer: 'A',
    explanation: '0/1 Knapsack fills a 2D table of size (N+1) x (W+1), taking O(N * W) pseudo-polynomial time, which can be space-optimized to a 1D array of size O(W).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'Knapsack'],
  },
  {
    questionText: 'What is the time complexity to find the Longest Common Subsequence (LCS) of two strings of lengths M and N using Dynamic Programming?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'LCS',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(M * N)' },
      { id: 'B', text: 'O(M + N)' },
      { id: 'C', text: 'O(2^(M + N))' },
      { id: 'D', text: 'O(M log N)' },
    ],
    correctAnswer: 'A',
    explanation: 'The DP state dp[i][j] stores LCS length of prefixes of lengths i and j. Filling the M x N grid takes O(M * N) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'LCS'],
  },
  {
    questionText: 'What is the most optimal time complexity to find the length of the Longest Increasing Subsequence (LIS) in an array of size n?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'LIS',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(n log n) using Patience Sorting / Binary Search (std::lower_bound)' },
      { id: 'B', text: 'O(n²) using standard DP' },
      { id: 'C', text: 'O(2ⁿ) brute force' },
      { id: 'D', text: 'O(n) linear time' },
    ],
    correctAnswer: 'A',
    explanation: 'Maintaining a tails array of active end elements and replacing elements via binary search computes LIS in O(n log n) time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'LIS', 'Hard'],
  },
  {
    questionText: 'In the Coin Change Problem (minimum coins for target amount A with C coin denominations), what is the DP time complexity?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'Coin Change',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(A * C)' },
      { id: 'B', text: 'O(2^A)' },
      { id: 'C', text: 'O(A + C)' },
      { id: 'D', text: 'O(C log A)' },
    ],
    correctAnswer: 'A',
    explanation: 'For every sub-amount from 1 to A, we try all C coin denominations: dp[i] = min(dp[i], 1 + dp[i - coin]), requiring O(A * C) operations.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'Coin Change'],
  },
  {
    questionText: 'What is the distinction between Memoization (Top-Down) and Tabulation (Bottom-Up)?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'Paradigms',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Memoization uses recursion + cache; Tabulation uses iteration + table' },
      { id: 'B', text: 'Memoization is O(2ⁿ); Tabulation is O(1)' },
      { id: 'C', text: 'Memoization only works for arrays' },
      { id: 'D', text: 'Tabulation requires stack recursion' },
    ],
    correctAnswer: 'A',
    explanation: 'Top-down memoization stores results of recursive function calls on demand. Bottom-up tabulation iteratively fills base cases up to the target state.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'Memoization'],
  },
  {
    questionText: 'What is the recurrence relation for the Edit Distance (Levenshtein Distance) between strings s1 and s2 when s1[i-1] != s2[j-1]?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'Edit Distance',
    difficulty: 'hard',
    options: [
      { id: 'A', text: '1 + min(dp[i-1][j] (delete), dp[i][j-1] (insert), dp[i-1][j-1] (replace))' },
      { id: 'B', text: 'dp[i-1][j-1] + 1' },
      { id: 'C', text: 'min(dp[i-1][j], dp[i][j-1])' },
      { id: 'D', text: 'dp[i-1][j-1] * 2' },
    ],
    correctAnswer: 'A',
    explanation: 'If characters mismatch, we take the minimum cost of three possible operations: deletion (dp[i-1][j]), insertion (dp[i][j-1]), or substitution (dp[i-1][j-1]) plus 1.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'Edit Distance'],
  },
  {
    questionText: 'What is the time complexity to find the Matrix Chain Multiplication order of n matrices?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'MCM',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'O(n³)' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(2ⁿ)' },
      { id: 'D', text: 'O(n log n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Matrix Chain Multiplication tests all possible split points k for chain lengths l = 2 to n, yielding O(n³) operations.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'MCM'],
  },
  {
    questionText: 'In the House Robber problem (cannot rob two adjacent houses), what is the optimal DP transition?',
    questionType: 'mcq',
    topicName: 'Dynamic Programming',
    subTopic: 'Linear DP',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'dp[i] = max(dp[i-1], nums[i] + dp[i-2])' },
      { id: 'B', text: 'dp[i] = nums[i] + dp[i-1]' },
      { id: 'C', text: 'dp[i] = max(nums[i], dp[i-1])' },
      { id: 'D', text: 'dp[i] = dp[i-1] * nums[i]' },
    ],
    correctAnswer: 'A',
    explanation: 'At house i, the robber either skips it (taking dp[i-1]) or robs it (adding nums[i] to optimal loot from house i-2).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'House Robber'],
  },
  {
    questionText: 'Fractional Knapsack can be solved using Dynamic Programming, while 0/1 Knapsack must be solved with Greedy.',
    questionType: 'true_false',
    topicName: 'Dynamic Programming',
    subTopic: 'Greedy vs DP',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False (Fractional is Greedy; 0/1 is DP)' },
    ],
    correctAnswer: 'B',
    explanation: 'False. Fractional Knapsack satisfies the greedy choice property (sort by value/weight). 0/1 Knapsack cannot be solved greedily and requires DP.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['DP', 'Greedy'],
  },

  // ==========================================
  // 8. RECURSION & BACKTRACKING (10 Questions)
  // ==========================================
  {
    questionText: 'What is the minimum number of moves required to solve the Tower of Hanoi puzzle with n disks?',
    questionType: 'mcq',
    topicName: 'Recursion',
    subTopic: 'Tower of Hanoi',
    difficulty: 'easy',
    options: [
      { id: 'A', text: '2ⁿ - 1' },
      { id: 'B', text: '2ⁿ' },
      { id: 'C', text: 'n²' },
      { id: 'D', text: 'n!' },
    ],
    correctAnswer: 'A',
    explanation: 'The recurrence T(n) = 2T(n-1) + 1 with T(1) = 1 yields T(n) = 2ⁿ - 1 moves.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Recursion', 'Hanoi'],
  },
  {
    questionText: 'What is Tail Recursion?',
    questionType: 'mcq',
    topicName: 'Recursion',
    subTopic: 'Tail Call Optimization',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'A recursive call that is the very last operation executed in the function' },
      { id: 'B', text: 'A function that calls itself twice' },
      { id: 'C', text: 'A function with infinite recursion' },
      { id: 'D', text: 'Recursion using heap allocation' },
    ],
    correctAnswer: 'A',
    explanation: 'In tail recursion, the function returns the result of the recursive call directly without needing to perform operations after the call returns, allowing compilers to optimize stack frames to O(1) space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Recursion', 'TCO'],
  },
  {
    questionText: 'What is the time complexity of generating all subsets (Power Set) of a set containing n elements?',
    questionType: 'mcq',
    topicName: 'Backtracking',
    subTopic: 'Subsets',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n * 2ⁿ)' },
      { id: 'B', text: 'O(n!)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'There are 2ⁿ subsets, and copying each subset takes O(n) on average, resulting in O(n * 2ⁿ) total time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Backtracking', 'Subsets'],
  },
  {
    questionText: 'What is the time complexity of generating all permutations of an array of n distinct elements?',
    questionType: 'mcq',
    topicName: 'Backtracking',
    subTopic: 'Permutations',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n * n!)' },
      { id: 'B', text: 'O(2ⁿ)' },
      { id: 'C', text: 'O(nⁿ)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'There are n! permutations, and generating each permutation of length n takes O(n), giving O(n * n!).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Backtracking', 'Permutations'],
  },
  {
    questionText: 'How does Backtracking differ from pure exhaustive Brute-Force recursion?',
    questionType: 'mcq',
    topicName: 'Backtracking',
    subTopic: 'Pruning',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Backtracking prunes (abandons) candidate branches as soon as a constraint is violated' },
      { id: 'B', text: 'Backtracking never uses recursion' },
      { id: 'C', text: 'Backtracking only solves sorting problems' },
      { id: 'D', text: 'Backtracking runs in O(log n)' },
    ],
    correctAnswer: 'A',
    explanation: 'Backtracking builds candidates incrementally and abandons (backtracks) a branch as soon as it determines the candidate cannot yield a valid solution.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Backtracking', 'Pruning'],
  },
  {
    questionText: 'In the N-Queens problem on an N x N chessboard, how can diagonal conflicts be checked in O(1) time?',
    questionType: 'mcq',
    topicName: 'Backtracking',
    subTopic: 'N-Queens',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'Using hash sets/arrays for (row - col) and (row + col)' },
      { id: 'B', text: 'Scanning the entire board row by row in O(N²)' },
      { id: 'C', text: 'Using a binary search tree' },
      { id: 'D', text: 'Diagonal conflicts cannot be checked in O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'All squares on the same main diagonal share equal (row - col), and all squares on anti-diagonals share equal (row + col). Lookup in a boolean array is O(1).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Backtracking', 'N-Queens'],
  },
  {
    questionText: 'What is the base case in a recursive algorithm?',
    questionType: 'mcq',
    topicName: 'Recursion',
    subTopic: 'Fundamentals',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'The terminating condition where the problem is solved directly without further recursive calls' },
      { id: 'B', text: 'The first line of the main function' },
      { id: 'C', text: 'The highest exponent in the recurrence relation' },
      { id: 'D', text: 'The point where memory runs out' },
    ],
    correctAnswer: 'A',
    explanation: 'Base cases stop the recursion chain. Without a valid base case, infinite recursion leads to stack overflow.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Recursion', 'Base Case'],
  },
  {
    questionText: 'What is the time complexity of solving a 9x9 Sudoku puzzle using Backtracking in the worst case?',
    questionType: 'mcq',
    topicName: 'Backtracking',
    subTopic: 'Sudoku',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(9^(m)) where m is the number of empty cells' },
      { id: 'B', text: 'O(N!)' },
      { id: 'C', text: 'O(1) polynomial' },
      { id: 'D', text: 'O(81)' },
    ],
    correctAnswer: 'A',
    explanation: 'Each empty cell has up to 9 possible digits (1 to 9). With m empty cells, the state tree explores up to 9^m combinations pruned by valid constraints.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Backtracking', 'Sudoku'],
  },
  {
    questionText: 'Can any recursive function be converted into an iterative function using an explicit Stack?',
    questionType: 'true_false',
    topicName: 'Recursion',
    subTopic: 'Stack Equivalence',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False' },
    ],
    correctAnswer: 'A',
    explanation: 'True. Any recursive process uses the call stack implicitly, and can thus be modeled iteratively using a user-managed explicit Stack data structure.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Recursion', 'Call Stack'],
  },
  {
    questionText: 'What is the time complexity of the Naive Recursive Fibonacci algorithm without memoization?',
    questionType: 'mcq',
    topicName: 'Recursion',
    subTopic: 'Fibonacci',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(2ⁿ) exponential (golden ratio φⁿ)' },
      { id: 'B', text: 'O(n)' },
      { id: 'C', text: 'O(n log n)' },
      { id: 'D', text: 'O(1)' },
    ],
    correctAnswer: 'A',
    explanation: 'Each call fib(n) spawns two calls fib(n-1) and fib(n-2), creating a binary recursion tree of depth n with ~2ⁿ total calls.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Recursion', 'Fibonacci'],
  },

  // ==========================================
  // 9. STRINGS, HASHING, COMPLEXITY (10 Questions)
  // ==========================================
  {
    questionText: 'What is the average time complexity of insertion, deletion, and lookup in a well-distributed Hash Table?',
    questionType: 'mcq',
    topicName: 'Hashing',
    subTopic: 'Hash Table Operations',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(1) average time' },
      { id: 'B', text: 'O(log n)' },
      { id: 'C', text: 'O(n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    correctAnswer: 'A',
    explanation: 'With a uniform hash function and load factor < threshold, average bucket lookup is O(1).',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Hashing', 'Complexity'],
  },
  {
    questionText: 'What is the Load Factor (α) of a Hash Table with n keys and m buckets?',
    questionType: 'mcq',
    topicName: 'Hashing',
    subTopic: 'Load Factor',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'α = n / m' },
      { id: 'B', text: 'α = m / n' },
      { id: 'C', text: 'α = n * m' },
      { id: 'D', text: 'α = log(n/m)' },
    ],
    correctAnswer: 'A',
    explanation: 'The load factor α = n / m measures the average number of elements stored per bucket. When α exceeds 0.75, rehashing to double capacity is triggered.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Hashing', 'Load Factor'],
  },
  {
    questionText: 'Which algorithm finds pattern occurrences in text of length N with pattern length M in O(N + M) time using a Partial Match (LPS) table?',
    questionType: 'mcq',
    topicName: 'Strings',
    subTopic: 'Pattern Matching',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'KMP (Knuth-Morris-Pratt) Algorithm' },
      { id: 'B', text: 'Brute Force String Matcher' },
      { id: 'C', text: 'Binary Search' },
      { id: 'D', text: "Floyd's Algorithm" },
    ],
    correctAnswer: 'A',
    explanation: 'KMP precomputes the Longest Prefix which is also Suffix (LPS array) in O(M), preventing redundant character comparisons in O(N + M) total time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Strings', 'KMP', 'Hard'],
  },
  {
    questionText: 'What is the time complexity to check if two strings of length n are valid Anagrams using frequency counting?',
    questionType: 'mcq',
    topicName: 'Strings',
    subTopic: 'Anagrams',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'O(n) time and O(1) space (26 lowercase character counts)' },
      { id: 'B', text: 'O(n log n)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'Incrementing counts for string 1 and decrementing for string 2 using a 26-element array takes O(n) time and O(1) auxiliary space.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Strings', 'Anagrams'],
  },
  {
    questionText: 'According to the Master Theorem, what is the time complexity for the recurrence relation T(n) = 2T(n/2) + O(n)?',
    questionType: 'mcq',
    topicName: 'Time Complexity',
    subTopic: 'Master Theorem',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n log n) (Case 2: log_b(a) = log₂(2) = 1, matches f(n) = n)' },
      { id: 'B', text: 'O(n)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(log n)' },
    ],
    correctAnswer: 'A',
    explanation: 'In T(n) = aT(n/b) + f(n), a=2, b=2. n^(log_b a) = n¹ = f(n). By Master Theorem Case 2, T(n) = O(n log n). This is the exact recurrence of Merge Sort.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Complexity', 'Master Theorem'],
  },
  {
    questionText: 'Which complexity class represents problems that can be solved in polynomial time by a deterministic Turing machine?',
    questionType: 'mcq',
    topicName: 'Introduction to Algorithms',
    subTopic: 'Complexity Classes',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'P (Polynomial Time)' },
      { id: 'B', text: 'NP' },
      { id: 'C', text: 'NP-Complete' },
      { id: 'D', text: 'EXPTIME' },
    ],
    correctAnswer: 'A',
    explanation: 'P is the complexity class containing all decision problems solvable by a deterministic algorithm in O(n^k) polynomial time.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Theory', 'P vs NP'],
  },
  {
    questionText: 'What is the time complexity to find the length of the longest substring without repeating characters in string s of length n?',
    questionType: 'mcq',
    topicName: 'Strings',
    subTopic: 'Sliding Window',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'O(n) time and O(min(m, n)) space using Sliding Window with HashMap' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(n³)' },
      { id: 'D', text: 'O(2ⁿ)' },
    ],
    correctAnswer: 'A',
    explanation: 'A sliding window with left and right pointers updates character last seen index in a hash map in O(n) single pass.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Strings', 'Sliding Window'],
  },
  {
    questionText: 'Which collision resolution method stores all colliding keys in a linked list attached to the bucket index?',
    questionType: 'mcq',
    topicName: 'Hashing',
    subTopic: 'Collision Resolution',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Separate Chaining' },
      { id: 'B', text: 'Linear Probing' },
      { id: 'C', text: 'Quadratic Probing' },
      { id: 'D', text: 'Double Hashing' },
    ],
    correctAnswer: 'A',
    explanation: 'Separate chaining creates a linked list (or red-black tree in Java 8 HashMap) at each bucket slot to hold colliding key-value entries.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Hashing', 'Chaining'],
  },
  {
    questionText: 'What is Big-O notation used to express?',
    questionType: 'mcq',
    topicName: 'Time Complexity',
    subTopic: 'Asymptotic Notation',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Upper bound on the asymptotic growth rate of an algorithm' },
      { id: 'B', text: 'Tight lower bound' },
      { id: 'C', text: 'Exact execution time in milliseconds' },
      { id: 'D', text: 'Hardware clock speed' },
    ],
    correctAnswer: 'A',
    explanation: 'Big-O describes the mathematical upper bound on algorithm time or memory complexity as the input size n approaches infinity.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Complexity', 'Big-O'],
  },
  {
    questionText: 'If algorithm A has time complexity O(n log n) and algorithm B has O(n²), algorithm A will always take fewer milliseconds than B for every possible input size n.',
    questionType: 'true_false',
    topicName: 'Time Complexity',
    subTopic: 'Constants & Asymptotics',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'True' },
      { id: 'B', text: 'False (Constant factors and small n can make O(n²) faster for tiny inputs)' },
    ],
    correctAnswer: 'B',
    explanation: 'False. Asymptotic notations ignore constant factors and lower-order terms. For small n (e.g. n < 16), Insertion Sort O(n²) often runs faster than Quick/Merge Sort due to lower constant overhead.',
    marks: 1,
    negativeMarks: 0.25,
    tags: ['Complexity', 'Constants'],
  },
];

module.exports = questionsData;
