const topicsData = [
  {
    order: 1,
    name: 'Introduction to Algorithms',
    slug: 'intro-to-algorithms',
    description: 'Fundamental concepts of algorithm design, correctness proofs, problem-solving paradigms, and asymptotic modeling.',
    category: 'Foundations',
    difficulty: 'Beginner',
    icon: 'Compass',
    keyConcepts: ['Algorithm Definition', 'Flowcharts & Pseudocode', 'Correctness Proofs', 'Loop Invariants'],
  },
  {
    order: 2,
    name: 'Time Complexity',
    slug: 'time-complexity',
    description: 'Asymptotic analysis, Big-O, Big-Omega, Big-Theta notations, Master Theorem, and recurrence relations.',
    category: 'Foundations',
    difficulty: 'Beginner',
    icon: 'Clock',
    keyConcepts: ['Big-O Notation', 'Big-Omega & Big-Theta', 'Master Theorem', 'Amortized Complexity'],
  },
  {
    order: 3,
    name: 'Space Complexity',
    slug: 'space-complexity',
    description: 'Auxiliary memory versus input memory, recursion call stack overhead, and in-place algorithmic optimizations.',
    category: 'Foundations',
    difficulty: 'Beginner',
    icon: 'HardDrive',
    keyConcepts: ['Auxiliary Space', 'Call Stack Space', 'In-place Algorithms', 'Memory Footprint'],
  },
  {
    order: 4,
    name: 'Arrays',
    slug: 'arrays',
    description: 'Static & dynamic arrays, contiguous memory allocation, prefix sums, two pointers, and multi-dimensional matrices.',
    category: 'Linear Data Structures',
    difficulty: 'Beginner',
    icon: 'Grid',
    keyConcepts: ['Two Pointers', 'Prefix Sums', "Kadane's Algorithm", 'Sliding Window', 'Matrix Traversal'],
  },
  {
    order: 5,
    name: 'Strings',
    slug: 'strings',
    description: 'String manipulation, string hashing, pattern matching (KMP, Rabin-Karp), anagrams, and palindrome checks.',
    category: 'Linear Data Structures',
    difficulty: 'Beginner',
    icon: 'Type',
    keyConcepts: ['ASCII & Unicode', 'String Hashing', 'Two Pointers', 'KMP Pattern Search'],
  },
  {
    order: 6,
    name: 'Linked Lists',
    slug: 'linked-lists',
    description: 'Singly, doubly, and circular linked lists, node pointer manipulation, cycle detection, and reversal techniques.',
    category: 'Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'Link',
    keyConcepts: ['Singly Linked List', 'Doubly Linked List', 'Floyd Cycle Detection', 'In-place Reversal'],
  },
  {
    order: 7,
    name: 'Stacks',
    slug: 'stacks',
    description: 'LIFO data structure, expression parsing (infix/postfix), monotonic stacks, and parentheses matching.',
    category: 'Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'Layers',
    keyConcepts: ['LIFO Principle', 'Monotonic Stack', 'Postfix Evaluation', 'Min Stack'],
  },
  {
    order: 8,
    name: 'Queues',
    slug: 'queues',
    description: 'FIFO principle, circular queues, double-ended queues (deque), and priority queues.',
    category: 'Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'ArrowRightCircle',
    keyConcepts: ['FIFO Principle', 'Circular Queue', 'Deque', 'Queue using Stacks'],
  },
  {
    order: 9,
    name: 'Recursion',
    slug: 'recursion',
    description: 'Base cases, recursive leap of faith, call stack frames, tree recursion, and tail recursion elimination.',
    category: 'Algorithms',
    difficulty: 'Intermediate',
    icon: 'Repeat',
    keyConcepts: ['Base Cases', 'Call Stack Frames', 'Tower of Hanoi', 'Tail Recursion'],
  },
  {
    order: 10,
    name: 'Searching',
    slug: 'searching',
    description: 'Linear search, binary search on sorted arrays and monotonic solution spaces, and exponential search.',
    category: 'Algorithms',
    difficulty: 'Beginner',
    icon: 'Search',
    keyConcepts: ['Linear Search', 'Binary Search', 'Search in Rotated Array', 'Binary Search on Answer'],
  },
  {
    order: 11,
    name: 'Sorting',
    slug: 'sorting',
    description: 'Comparison and non-comparison sorting: Bubble, Selection, Insertion, Merge, Quick, Heap, and Radix Sort.',
    category: 'Algorithms',
    difficulty: 'Intermediate',
    icon: 'ArrowUpDown',
    keyConcepts: ['Merge Sort', 'Quick Sort', 'Heap Sort', 'Sorting Stability', 'Lower Bound O(n log n)'],
  },
  {
    order: 12,
    name: 'Hashing',
    slug: 'hashing',
    description: 'Hash tables, collision resolution techniques (chaining, open addressing), load factor, and frequency maps.',
    category: 'Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'Hash',
    keyConcepts: ['Hash Functions', 'Chaining & Probing', 'Load Factor & Rehashing', 'Two Sum HashMap'],
  },
  {
    order: 13,
    name: 'Trees',
    slug: 'trees',
    description: 'Binary trees, traversals (Inorder, Preorder, Postorder, Level Order), tree height, and diameter.',
    category: 'Non-Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'GitBranch',
    keyConcepts: ['Tree Traversals', 'Tree Height & Diameter', 'Lowest Common Ancestor (LCA)', 'Subtree Problems'],
  },
  {
    order: 14,
    name: 'Binary Search Trees',
    slug: 'binary-search-trees',
    description: 'BST invariants, insertion, deletion (with 2 children), validation, AVL trees, and Red-Black balancing.',
    category: 'Non-Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'Binary',
    keyConcepts: ['BST Invariant', 'Inorder Successor', 'Node Deletion', 'AVL & Self-Balancing Trees'],
  },
  {
    order: 15,
    name: 'Heaps',
    slug: 'heaps',
    description: 'Min-heaps, max-heaps, complete binary tree array representation, heapify operation, and top-K elements.',
    category: 'Non-Linear Data Structures',
    difficulty: 'Intermediate',
    icon: 'Triangle',
    keyConcepts: ['Min/Max Heap', 'Array Indexing (2i+1, 2i+2)', 'Heapify in O(n)', 'Top-K Elements'],
  },
  {
    order: 16,
    name: 'Graphs',
    slug: 'graphs',
    description: 'Adjacency list, adjacency matrix, connected components, bipartite graphs, and topological sorting.',
    category: 'Non-Linear Data Structures',
    difficulty: 'Advanced',
    icon: 'Share2',
    keyConcepts: ['Adjacency List/Matrix', 'Degree & Connectivity', 'Bipartite Graphs', 'Topological Sort (Kahn)'],
  },
  {
    order: 17,
    name: 'BFS',
    slug: 'bfs',
    description: 'Breadth-First Search on graphs and grid matrices, shortest path in unweighted graphs, and multi-source BFS.',
    category: 'Algorithms',
    difficulty: 'Intermediate',
    icon: 'Radio',
    keyConcepts: ['Queue-based Traversal', 'Shortest Path Unweighted', 'Level Order BFS', 'Multi-Source BFS'],
  },
  {
    order: 18,
    name: 'DFS',
    slug: 'dfs',
    description: 'Depth-First Search, recursion, cycle detection in directed/undirected graphs, and connected component counts.',
    category: 'Algorithms',
    difficulty: 'Intermediate',
    icon: 'Compass',
    keyConcepts: ['Call Stack Traversal', 'Cycle Detection in Directed Graphs', 'Flood Fill', 'Component Counting'],
  },
  {
    order: 19,
    name: 'Greedy Algorithms',
    slug: 'greedy-algorithms',
    description: 'Locally optimal choice property, activity selection, fractional knapsack, Dijkstra, and Kruskal/Prim MST.',
    category: 'Advanced Techniques',
    difficulty: 'Intermediate',
    icon: 'TrendingUp',
    keyConcepts: ['Optimal Substructure', 'Activity Selection', 'Fractional Knapsack', 'Huffman Coding'],
  },
  {
    order: 20,
    name: 'Divide and Conquer',
    slug: 'divide-and-conquer',
    description: 'Breaking problems into independent subproblems: Merge sort, Quick sort, Karatsuba multiplication, and median finding.',
    category: 'Advanced Techniques',
    difficulty: 'Intermediate',
    icon: 'Scissors',
    keyConcepts: ['Divide, Conquer, Combine', 'Merge Sort', 'Quick Select', 'Matrix Multiplication'],
  },
  {
    order: 21,
    name: 'Dynamic Programming',
    slug: 'dynamic-programming',
    description: 'Overlapping subproblems, memoization vs tabulation, state definition, 0/1 Knapsack, LCS, and LIS.',
    category: 'Advanced Techniques',
    difficulty: 'Advanced',
    icon: 'Cpu',
    keyConcepts: ['State Transition', 'Memoization & Tabulation', '0/1 Knapsack', 'LCS & LIS', 'Grid DP'],
  },
  {
    order: 22,
    name: 'Backtracking',
    slug: 'backtracking',
    description: 'State space tree exploration, pruning infeasible branches, N-Queens problem, Sudoku solver, and permutations/subsets.',
    category: 'Advanced Techniques',
    difficulty: 'Advanced',
    icon: 'ShieldAlert',
    keyConcepts: ['State Space Tree', 'Pruning Infeasible Paths', 'N-Queens', 'Subset & Permutation Generation'],
  },
];

module.exports = topicsData;
